config/routes.rb
Rails.application.routes.draw do
  resources :vehicles do
    match '/scrape', to: 'vehicles#scrape', via: :post, on: :collection
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: 'vehicles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/models/vehicles_spider.rb
class VehiclesSpider < Kimurai::Base
  @name = 'vehicles_spider'
  @engine = :mechanize

  def self.process(url)
    @start_urls = [url]
    self.crawl!
  end

  def parse(response, url:, data: {})
    response.xpath("//div[@class='shop-srp-listings__listing-container']").each do |vehicle|
      item = {}

      item[:title]      = vehicle.css('h2.listing-row__title')&.text&.squish
      item[:price]      = vehicle.css('span.listing-row__price')&.text&.squish&.delete('^0-9').to_i
      item[:stock_type] = vehicle.css('div.listing-row__stocktype')&.text&.squish
      item[:miles]      = vehicle.css('span.listing-row__mileage')&.text&.squish&.delete('^0-9').to_i
      item[:exterior_color] = vehicle.css('ul.listing-row__meta li')[0]&.text&.squish.gsub('Ext. Color: ', '')
      item[:interior_color] = vehicle.css('ul.listing-row__meta li')[1]&.text&.squish.gsub('Int. Color: ', '')
      item[:transmission] = vehicle.css('ul.listing-row__meta li')[2]&.text&.squish.gsub('Transmission: ', '')
      item[:drivetrain]   = vehicle.css('ul.listing-row__meta li')[3]&.text&.squish.gsub('Drivetrain: ', '')

      Vehicle.where(item).first_or_create
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: %i[ show edit update destroy ]

  # GET /vehicles or /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  def scrape
    byebug
    url = 'https://www.cars.com/shopping/sedan/'
    response = VehiclesSpider.process(url)
    if response[:status] == :completed && response[:error].nil?
      flash.now[:notice] = "Successfully scraped url"
    else
      flash.now[:alert] = response[:error]
    end
  rescue StandardError => e
    flash.now[:alert] = "Error: #{e}"
  end

  # GET /vehicles/1 or /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles or /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to vehicle_url(@vehicle), notice: "Vehicle was successfully created." }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1 or /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to vehicle_url(@vehicle), notice: "Vehicle was successfully updated." }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1 or /vehicles/1.json
  def destroy
    @vehicle.destroy

    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: "Vehicle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_params
      params.require(:vehicle).permit(:title, :stock_type, :exterior_color, :interior_color, :transmission, :drivetrain, :price, :miles)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebScraper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle) do |form| %>
  <% if vehicle.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
        <% vehicle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :stock_type, style: "display: block" %>
    <%= form.text_field :stock_type %>
  </div>

  <div>
    <%= form.label :exterior_color, style: "display: block" %>
    <%= form.text_field :exterior_color %>
  </div>

  <div>
    <%= form.label :interior_color, style: "display: block" %>
    <%= form.text_field :interior_color %>
  </div>

  <div>
    <%= form.label :transmission, style: "display: block" %>
    <%= form.text_field :transmission %>
  </div>

  <div>
    <%= form.label :drivetrain, style: "display: block" %>
    <%= form.text_field :drivetrain %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :miles, style: "display: block" %>
    <%= form.number_field :miles %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/_vehicle.html.erb
<div id="<%= dom_id vehicle %>">
  <p>
    <strong>Title:</strong>
    <%= vehicle.title %>
  </p>

  <p>
    <strong>Stock type:</strong>
    <%= vehicle.stock_type %>
  </p>

  <p>
    <strong>Exterior color:</strong>
    <%= vehicle.exterior_color %>
  </p>

  <p>
    <strong>Interior color:</strong>
    <%= vehicle.interior_color %>
  </p>

  <p>
    <strong>Transmission:</strong>
    <%= vehicle.transmission %>
  </p>

  <p>
    <strong>Drivetrain:</strong>
    <%= vehicle.drivetrain %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= vehicle.price %>
  </p>

  <p>
    <strong>Miles:</strong>
    <%= vehicle.miles %>
  </p>

</div>

app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<%= render "form", vehicle: @vehicle %>

<br>

<div>
  <%= link_to "Show this vehicle", @vehicle %> |
  <%= link_to "Back to vehicles", vehicles_path %>
</div>

app/views/vehicles/index.html.erb
<p style="color: green"><%= notice %></p>

<%= button_to 'Scrape', scrape_vehicles_path %>

<h1>Vehicles</h1>

<div id="vehicles">
  <% @vehicles.each do |vehicle| %>
    <%= render vehicle %>
    <p>
      <%= link_to "Show this vehicle", vehicle %>
    </p>
  <% end %>
</div>

<%= link_to "New vehicle", new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New vehicle</h1>

<%= render "form", vehicle: @vehicle %>

<br>

<div>
  <%= link_to "Back to vehicles", vehicles_path %>
</div>

app/views/vehicles/scrape.html.erb
<p id='notice'><%= notice %></p>
<p id='alert'><%= alert %></p>

<%= link_to 'Go Back', root_path%>

app/views/vehicles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @vehicle %>

<div>
  <%= link_to "Edit this vehicle", edit_vehicle_path(@vehicle) %> |
  <%= link_to "Back to vehicles", vehicles_path %>

  <%= button_to "Destroy this vehicle", @vehicle, method: :delete %>
</div>